import type { WikiPhase } from "../wiki-types.ts";
import { reviewPrompt } from "../answer-validation.ts";

const topic = `{title,aliases:string[],subjectKey,aspectKey,question,inclusion,exclusion,handles:string[],identities:[],identityRequired:false}`;
export const prompts: Record<WikiPhase, string> = {
  generation: `Generate a concise source-grounded answer to pack.question, or a Wiki block when topic is supplied. Return JSON {segments:[{id,text,role:"fact"|"gap"|"question",handles:string[],subject,scope,conditions:string[],attribution:"source"|"inference",premises:string[]}]}. Each segment is one complete assertion; segments are joined by a newline. Include every material qualification in the text itself. Facts must cite original handles, inferences must list prerequisite segment IDs. Cite no invented handles. Do not use inline citation markers; handles carry citations. For Wiki generate body segments only, without any heading. The host prepends the fixed topic title as a separate claim with reserved ID wiki-heading; never use that ID. That heading is also independently reviewed. Preserve requiredConflict with a distinct assertion citing all its handles; never silently resolve a conflict. A gap is genuinely absent evidence, not a way to relabel unsupported facts. For ordinary answers use at most 3 short segments and keep the full JSON under 1400 UTF-8 bytes; Wiki prose under 4000 bytes. Use the user's language. Respect supplied feedback without copying an unsupported claim.`,
  review: `${reviewPrompt} Return JSON {draftHash,evidenceHash,unlistedClaims:string[],claims:[{id,verdict:"supported"|"contradicted"|"insufficient",standalone:boolean,reason,spans:[{handle,quote}]}]}. Echo draft.hash and pack.hash. Review EVERY claim including title/gap claims and all prose. Support means semantic entailment, not exact wording: faithful paraphrases are allowed. A Wiki heading with scope 主题目录标签 is a topic label summarizing the cited content, NOT a claim that an original document had that exact title. Support it only when the original subject and scope justify the label; reject any added entities or qualifications. Quotes must be exact nonempty unique substrings of the cited original item's text; include all original handles supporting each fact. Empty spans are allowed for genuine gaps. Do not calculate character offsets. Never approve merely because a citation exists. Keep reasons short. For non-Wiki answers keep the complete result below 1900 UTF-8 bytes.`,
  extraction: `Identify at most 4 independently useful topics in pack.items. Return {topics:[${topic}],coverage:[{handle,topicIndexes:number[],outcome:"assigned"|"context"|"unresolved"}]}. Account for every original handle exactly once; assigned handles must match topic.handles and indexes. Group by subject, reader question and applicability rather than document name. Do not manufacture identity proof IDs; use empty identities unless supplied proofs establish identity. Preserve scope and uncertainty; mark unresolved material explicitly.`,
  planning: `Choose one action create|update|revalidate|link|no_change|defer for topic using only the supplied candidate catalogue and inspections. Prefer compatible reuse. Return {action,pageId?:string,reason,contribution:{handles:string[],claim,question,substantive:true},assessments:[[candidateIndex,[subjectCompatible,aspectCompatible,scopeCompatible,boundaryCompatible],addedClaims:string[],revisedClaims:string[],conflictingClaims:string[],reason]],proposals?:[{kind:"merge"|"split",pageIds:string[],reason}]}. Include one assessment for EVERY candidate, with four booleans and concise reasons. When candidates is empty, assessments MUST be []. Never invent candidate entries. Do not create when a candidate is fully compatible. Stale prose is routing context, not evidence. A bounded search does not prove global absence; defer if uncertain. Keep output below 2000 UTF-8 bytes.`,
  inspection: `Inspect every range in window for topic applicability, including original context and current page boundaries. Return {windowHash,complete:boolean,reason,remaining:[],relevant:[{range:number,start:number,end:number}]}. Echo windowHash. Relevant spans use zero-based UTF-16 offsets local to that range's text. If unsure of a partial offset select the full relevant range. Mark incomplete rather than pretending to inspect unavailable material. Page prose and descriptors are only routing context.`,
  support: `Compare claim against CURRENT pack originals, including subject, scope, conditions and conflicts. Historical claim.originals are context, not current support. Return {claimId,claimVerdict:"supported"|"absent"|"unresolved",qualifiersChecked:boolean,claimReason,claimHandles:string[],evidenceHash,pageVersion,coverage:[{handle,outcome:"support"|"context"|"unresolved",reason}]}. Echo claim.id,pack.hash,pageVersion. Cover every current handle exactly once. Support coverage selects originals useful for this topic's refreshed prose, not merely exact text matches. Absence requires completed comparison; uncertainties remain unresolved.`,
  conflicts: `Compare every left/right handle pair against pack originals for contradictions within the SAME applicability. Different times/environments do not automatically conflict. Return {evidenceHash,pairs:[{left,right,verdict:"compatible"|"conflict"|"unresolved",scopeChecked:boolean,reason}]}. Echo pack.hash and include the entire Cartesian product exactly once. Never settle a disagreement by upload order.`,
  graph_extraction: `Extract explicit source relationships using the supplied mentions and originals. Return {relations:[{subjectMention,objectMention,predicate,direction:"forward"|"reverse",relationText,scope,qualifiers:{time?:string,environment?:string,conditions?:string,negated?:boolean,status?:"planned"|"current"|"historical"},locators:string[]}],exclusions:[{kind,reason,mention?:string}],complete:boolean}. Predicate must be from vocabulary. Use supplied mention UUIDs when available, never invent UUIDs or merge names across scopes. Locators are original passageId values, not handles. Preserve negation and qualifications. At most 20 relations; overflow must set complete=false. Report unsupported/unresolved relationships as exclusions, including exact missing endpoint names when no recorded mention is available. No transitive or world-knowledge edges.`,
  graph_review: `Independently verify EVERY packet.relations entry against the original array pack, including endpoint mentions, direction, scope, negation, time and conditions. Resolve subjectMention/objectMention UUIDs using the supplied trusted mentions catalogue and original positions. Correct relationText alone does not justify incorrect or swapped UUID bindings; reject a reversed edge even when its prose is correct. An unmapped endpoint cannot be approved. Return {evidenceHash,complete:boolean,relations:[{verdict:"supported"|"contradicted"|"insufficient",qualifiersChecked:boolean}]}, in the same order. Echo the supplied relationsHash. Do not approve missing evidence or inferred relationships.`,
  structure: `Plan the requested kind merge|split using original pack and supplied claims. Return {kind,reason,equivalentSubject:boolean,equivalentAspect:boolean,equivalentApplicability:boolean,overlap:[{left:claimId,right:claimId}],successors:[{topic:${topic},claimIds:string[],independent:boolean}]}. Preserve ALL claims and all conflicts and qualifiers. Merge requires equivalent subject/aspect/applicability and supported overlap connecting pages; split needs 2-4 independently useful topics and cannot separate a conflict from its premises. Do not propose a structure unsupported by originals.`,
  structure_review: `Independently review plan and all claims against pack originals. If published is absent return {planHash,evidenceHash,boundariesSupported:boolean,problems:string[],claims:[{id,verdict:"supported"|"contradicted"|"insufficient",qualifiersChecked:boolean}],overlapSupported:boolean}. Echo planHash,pack.hash; overlapSupported is true only for a supported merge. If published is present instead return {planHash,evidenceHash,publishedHash,coverage:[{id,successor:number,verdict:"supported"|"contradicted"|"insufficient",qualifiersChecked:boolean,claimIds:string[]}]}. Echo supplied hashes. Cover every successor/required-claim obligation, pointing to actual published claim IDs preserving all original qualifications and conflict information. Do not approve on structural validity alone.`,
};
