import { PDFDocument, StandardFonts } from "pdf-lib";
import { hashData } from "../src/server/library";
const generated = [];
for (const [file, title, facts] of [
  [
    "conflicting-source.pdf",
    "Acme Independent Audit 2026",
    [
      "Acme 2026 revenue was 130 million USD.",
      "Audited domestic operations only, excluding subsidiaries.",
      "This source reports 2026 domestic net profit of 13 million USD.",
    ],
  ],
  [
    "other-company.pdf",
    "Beta Annual Report 2026",
    [
      "Beta 2026 revenue was 999 million EUR.",
      "It covers global operations including subsidiaries.",
      "This is Beta, not Acme. Do not combine different companies or currencies.",
    ],
  ],
] as const) {
  const pdf = await PDFDocument.create();
  pdf.setTitle(title);
  pdf.setAuthor("LoreWeave acceptance fixtures");
  pdf.setCreationDate(new Date("2026-01-01T00:00:00Z"));
  pdf.setModificationDate(new Date("2026-01-01T00:00:00Z"));
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const page = pdf.addPage([612, 792]);
  page.drawText(title, { x: 50, y: 725, size: 22, font: bold });
  facts.forEach((text, i) =>
    page.drawText(text, { x: 50, y: 670 - i * 25, size: 11, font: regular }),
  );
  const bytes = await pdf.save();
  await Bun.write(`tests/fixtures/pdf/${file}`, bytes);
  generated.push({
    file,
    sha256: hashData(bytes),
    pages: 1,
    origin:
      "Generated by scripts/generate-question-fixtures.ts; repository-authored synthetic evidence",
    license: "MIT (repository LICENSE)",
    facts,
  });
}
await Bun.write(
  "tests/fixtures/pdf/question-manifest.json",
  JSON.stringify({ revision: "2026-10-01-v1", fixtures: generated }, null, 2) +
    "\n",
);
