/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BaselineProbeRouteImport } from './routes/baseline-probe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as McpProbeRouteImport } from './routes/mcp-probe'
import { Route as AppConversationRouteImport } from './routes/_app.conversation'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as ApiDocumentsRouteImport } from './routes/api.documents'
import { Route as ApiProbeRouteImport } from './routes/api.probe'
import { Route as AppOriginalVersionIdRouteImport } from './routes/_app.original.$versionId'
import { Route as ApiDocumentVersionsIdOriginalRouteImport } from './routes/api.document-versions.$id.original'
import { Route as ApiDocumentsIdUpdatesRouteImport } from './routes/api.documents.$id.updates'
import { Route as ApiRunsIdEventsRouteImport } from './routes/api.runs.$id.events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineProbeRoute = BaselineProbeRouteImport.update({
  id: '/baseline-probe',
  path: '/baseline-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const McpProbeRoute = McpProbeRouteImport.update({
  id: '/mcp-probe',
  path: '/mcp-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConversationRoute = AppConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProbeRoute = ApiProbeRouteImport.update({
  id: '/api/probe',
  path: '/api/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOriginalVersionIdRoute = AppOriginalVersionIdRouteImport.update({
  id: '/original/$versionId',
  path: '/original/$versionId',
  getParentRoute: () => AppRoute,
} as any)
const ApiDocumentVersionsIdOriginalRoute =
  ApiDocumentVersionsIdOriginalRouteImport.update({
    id: '/api/document-versions/$id/original',
    path: '/api/document-versions/$id/original',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsIdUpdatesRoute = ApiDocumentsIdUpdatesRouteImport.update({
  id: '/$id/updates',
  path: '/$id/updates',
  getParentRoute: () => ApiDocumentsRoute,
} as any)
const ApiRunsIdEventsRoute = ApiRunsIdEventsRouteImport.update({
  id: '/api/runs/$id/events',
  path: '/api/runs/$id/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baseline-probe': typeof BaselineProbeRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/mcp-probe': typeof McpProbeRoute
  '/conversation': typeof AppConversationRoute
  '/documents': typeof AppDocumentsRoute
  '/settings': typeof AppSettingsRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/probe': typeof ApiProbeRoute
  '/original/$versionId': typeof AppOriginalVersionIdRoute
  '/api/document-versions/$id/original': typeof ApiDocumentVersionsIdOriginalRoute
  '/api/documents/$id/updates': typeof ApiDocumentsIdUpdatesRoute
  '/api/runs/$id/events': typeof ApiRunsIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baseline-probe': typeof BaselineProbeRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/mcp-probe': typeof McpProbeRoute
  '/conversation': typeof AppConversationRoute
  '/documents': typeof AppDocumentsRoute
  '/settings': typeof AppSettingsRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/probe': typeof ApiProbeRoute
  '/original/$versionId': typeof AppOriginalVersionIdRoute
  '/api/document-versions/$id/original': typeof ApiDocumentVersionsIdOriginalRoute
  '/api/documents/$id/updates': typeof ApiDocumentsIdUpdatesRoute
  '/api/runs/$id/events': typeof ApiRunsIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/baseline-probe': typeof BaselineProbeRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/mcp-probe': typeof McpProbeRoute
  '/_app/conversation': typeof AppConversationRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/probe': typeof ApiProbeRoute
  '/_app/original/$versionId': typeof AppOriginalVersionIdRoute
  '/api/document-versions/$id/original': typeof ApiDocumentVersionsIdOriginalRoute
  '/api/documents/$id/updates': typeof ApiDocumentsIdUpdatesRoute
  '/api/runs/$id/events': typeof ApiRunsIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baseline-probe'
    | '/login'
    | '/mcp'
    | '/mcp-probe'
    | '/conversation'
    | '/documents'
    | '/settings'
    | '/api/documents'
    | '/api/probe'
    | '/original/$versionId'
    | '/api/document-versions/$id/original'
    | '/api/documents/$id/updates'
    | '/api/runs/$id/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baseline-probe'
    | '/login'
    | '/mcp'
    | '/mcp-probe'
    | '/conversation'
    | '/documents'
    | '/settings'
    | '/api/documents'
    | '/api/probe'
    | '/original/$versionId'
    | '/api/document-versions/$id/original'
    | '/api/documents/$id/updates'
    | '/api/runs/$id/events'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/baseline-probe'
    | '/login'
    | '/mcp'
    | '/mcp-probe'
    | '/_app/conversation'
    | '/_app/documents'
    | '/_app/settings'
    | '/api/documents'
    | '/api/probe'
    | '/_app/original/$versionId'
    | '/api/document-versions/$id/original'
    | '/api/documents/$id/updates'
    | '/api/runs/$id/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BaselineProbeRoute: typeof BaselineProbeRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  McpProbeRoute: typeof McpProbeRoute
  ApiDocumentsRoute: typeof ApiDocumentsRouteWithChildren
  ApiProbeRoute: typeof ApiProbeRoute
  ApiDocumentVersionsIdOriginalRoute: typeof ApiDocumentVersionsIdOriginalRoute
  ApiRunsIdEventsRoute: typeof ApiRunsIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline-probe': {
      id: '/baseline-probe'
      path: '/baseline-probe'
      fullPath: '/baseline-probe'
      preLoaderRoute: typeof BaselineProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-probe': {
      id: '/mcp-probe'
      path: '/mcp-probe'
      fullPath: '/mcp-probe'
      preLoaderRoute: typeof McpProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/conversation': {
      id: '/_app/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof AppConversationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/probe': {
      id: '/api/probe'
      path: '/api/probe'
      fullPath: '/api/probe'
      preLoaderRoute: typeof ApiProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/original/$versionId': {
      id: '/_app/original/$versionId'
      path: '/original/$versionId'
      fullPath: '/original/$versionId'
      preLoaderRoute: typeof AppOriginalVersionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/document-versions/$id/original': {
      id: '/api/document-versions/$id/original'
      path: '/api/document-versions/$id/original'
      fullPath: '/api/document-versions/$id/original'
      preLoaderRoute: typeof ApiDocumentVersionsIdOriginalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$id/updates': {
      id: '/api/documents/$id/updates'
      path: '/$id/updates'
      fullPath: '/api/documents/$id/updates'
      preLoaderRoute: typeof ApiDocumentsIdUpdatesRouteImport
      parentRoute: typeof ApiDocumentsRoute
    }
    '/api/runs/$id/events': {
      id: '/api/runs/$id/events'
      path: '/api/runs/$id/events'
      fullPath: '/api/runs/$id/events'
      preLoaderRoute: typeof ApiRunsIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppConversationRoute: typeof AppConversationRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppOriginalVersionIdRoute: typeof AppOriginalVersionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConversationRoute: AppConversationRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppOriginalVersionIdRoute: AppOriginalVersionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiDocumentsRouteChildren {
  ApiDocumentsIdUpdatesRoute: typeof ApiDocumentsIdUpdatesRoute
}

const ApiDocumentsRouteChildren: ApiDocumentsRouteChildren = {
  ApiDocumentsIdUpdatesRoute: ApiDocumentsIdUpdatesRoute,
}

const ApiDocumentsRouteWithChildren = ApiDocumentsRoute._addFileChildren(
  ApiDocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BaselineProbeRoute: BaselineProbeRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  McpProbeRoute: McpProbeRoute,
  ApiDocumentsRoute: ApiDocumentsRouteWithChildren,
  ApiProbeRoute: ApiProbeRoute,
  ApiDocumentVersionsIdOriginalRoute: ApiDocumentVersionsIdOriginalRoute,
  ApiRunsIdEventsRoute: ApiRunsIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
